<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * AttendanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttendanceRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array('isActive' => true), array('idIncrement' => 'DESC'));
    }

    public function findStatusOfAttendance($id, $dateSelected)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT attendance, userHasCourses
            FROM ApiBundle:Attendance attendance
            INNER JOIN attendance.userHasCourses userHasCourses
            WHERE
            userHasCourses.idIncrement = :id AND 
            attendance.optionDate LIKE :optionDate AND
            attendance.isActive = :isActive 
            ORDER BY attendance.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setMaxResults(1);
        $query->setParameter('id', $id);
        $query->setParameter('optionDate', $dateSelected .'%');
        $query->setParameter('isActive', 1);

        return $query->getOneOrNullResult();
    }

}
