<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GradesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradesRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array('isActive' => true), array('idIncrement' => 'DESC'));
    }

    public function findByCourseAndBimester($idUserHasCourses, $bimester)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT grades
            FROM ApiBundle:Grades grades
            WHERE
            grades.userHasCourses = :idUserHasCourses AND 
            grades.bimester = :bimester AND
            grades.isActive = :isActive 
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('idUserHasCourses', $idUserHasCourses);
        $query->setParameter('bimester', $bimester);
        $query->setParameter('isActive', 1);

        return $query->getResult();
    }


}
