<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserHasCoursesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasCoursesRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(['isActive' => true], ['idIncrement' => 'DESC']);
    }

    public function findCoursesByUser($id)
    {

        $em = $this->getEntityManager();
        $dql = "
            SELECT userHasCourses, courses, userProject
            FROM ApiBundle:UserHasCourses userHasCourses
            JOIN userHasCourses.user userProject
            JOIN userHasCourses.courses courses
            WHERE
            userProject.idIncrement = :id 
            ORDER BY courses.name ASC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);

        return $query->getResult();
    }

    public function findOneByUserAndCourse($idUser, $idCourse)
    {

        $em = $this->getEntityManager();
        $dql = "
            SELECT userHasCourses, userProject, courses
            FROM ApiBundle:UserHasCourses userHasCourses
            JOIN userHasCourses.user userProject
            JOIN userHasCourses.courses courses
            WHERE
            userProject.idIncrement = :idUser AND 
            courses.idIncrement = :idCourse 
            ";

        $query = $em->createQuery($dql);
        $query->setMaxResults(1);
        $query->setParameter('idUser', $idUser);
        $query->setParameter('idCourse', $idCourse);

        return $query->getOneOrNullResult();
    }

    public function findOneByCourse($idCourse)
    {

        $em = $this->getEntityManager();
        $dql = "
            SELECT userHasCourses, courses
            FROM ApiBundle:UserHasCourses userHasCourses
            JOIN userHasCourses.courses courses
            WHERE
            courses.idIncrement = :idCourse 
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('idCourse', $idCourse);

        return $query->getResult();
    }

    public function findAllUsersByCourse($idCourse, $idProfile)
    {

        $em = $this->getEntityManager();
        $dql = "
            SELECT userHasCourses, userProject, profile
            FROM ApiBundle:UserHasCourses userHasCourses
            JOIN userHasCourses.user userProject
            JOIN userProject.profile profile
            JOIN userHasCourses.courses courses
            WHERE
            courses.idIncrement = :idCourse AND 
            profile.idIncrement = :idProfile
            ORDER BY userProject.name, userProject.lastName DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('idCourse', $idCourse);
        $query->setParameter('idProfile', $idProfile);

        return $query->getResult();
    }

}
